Repository bbawuah/Pixby, pull requests merged in 2020-06, with the labels that each got.

#3 Dit is even een test..
  README.md
Labels: documentation

#4 testing pullrequest
  README.md
Labels: documentation

#7 splitting routes joanns feature
  .eslintrc.json
  index.js
Labels: Setup

#8 seperated functions from route (updateLike/dislike)
  index.js
Labels: bug

#9 seperate functions edited again lol
  index.js
Labels: duplicate

#13 Removing req.session
  index.js
  src/db/mongoose.js
Labels: Server setup

#16 Fixing like function
  index.js
Labels: bug

#22 Added unique id to route
  README.md
  index.js
  src/routes/home.js
  src/routes/likeAndMatch.js
  src/routes/profile.js
  views/index.hbs
  views/match.hbs
Labels: enhancement

#24 style like/dislike buttons
  public/main.css
Labels: enhancement

#26 added users/images
  public/img/components/caleb.png
  public/img/components/dirkjan.png
  public/img/components/duane.png
  public/img/components/jacob.png
  public/img/components/jason.png
  public/img/components/jimmy.png
  public/img/components/jordan.png
  public/img/components/kylo.png
  public/img/components/match-10.png
  public/img/components/match-11.png
  public/img/components/match-12.png
  public/img/components/match-13.png
  public/img/components/match-14.png
  public/img/components/match-15.png
  public/img/components/match-16.png
  public/img/components/match-7.png
  public/img/components/match-8.png
  public/img/components/match-9.png
  public/img/components/obi.png
  public/img/components/sam.png
Labels: enhancement

#28 fixed responsiveness
  public/main.css
Labels: enhancement

#40 like/match adjustments / comments to english
  public/img/components/5ce3ee71ed298bd6781d671afdbab0ea
  public/img/components/a4db9e6af4501ec977245ee7ad94a5dd
  src/routes/home.js
  src/routes/likeAndMatch.js
Labels: enhancement

#52 created launch page
  public/img/components/14338bb336219eea5fc170e94aacc097
  public/img/components/56c440e58c41804f682d093fd325e27f
  public/img/components/858a618b33ec7bef20e0fc2fab2a05e1
  public/img/components/924043a492c93c5fa0f89efa4fcee306
  public/main.css
  src/routes/index.js
  views/index.hbs
  views/match.hbs
  views/partials/header.hbs
  views/register.hbs
Labels: bug, enhancement
